language: python
dist: xenial

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: pypy
    - python: 3.7
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: 2.7
    - python: pypy
    - python: 3.8-dev
    - python: nightly

install:
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install -r requirements.txt
  - python -m pip install -r qa/requirements.txt

script:
  - set pipefail
  - export SKIPCLEANUP=exabgp
  - ./sbin/exabgp --fi | tee etc/exabgp/exabgp.env
  - ./sbin/exabgp --version
  - ./qa/bin/functional listing
  - ./qa/bin/functional all
  - ./qa/bin/parsing
  - env exabgp_tcp_bind='' ./sbin/exabgp decode ./etc/exabgp/api-open.conf  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003C:02:0000001C4001010040020040030465016501800404000000C840050400000064000000002001010101
  - env exabgp_log_enable=false nosetests --with-coverage ./tests/*_test.py

after_success:
  - coveralls

notifications:
  irc:
    channels: "irc.freenode.org#exabgp"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/48936e41bd3f866cce4e
    # options: [always|never|change] default: always
    on_success: always
    on_failure: always
    on_start: false

