language: python

python:
  - "2.7"
  - "3.7"
  - "pypy"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip python-dev
  - sudo apt-get install -y python3-pip python3-setuptools

install:
  - pip install -r requirements.txt
  - pip3 install -r requirements.txt
  - pip3 install -r qa/requirements.txt

script:
  - export INTERPRETER=python3
  - export SKIPCLEANUP=exabgp
  - sbin/exabgp --version
  - sbin/exabgp --fi > etc/exabgp/exabgp.env
  - set pipefail
  - ./qa/bin/parsing
  - ./qa/bin/functional all
  - env exabgp_tcp_bind='' ./sbin/exabgp ./etc/exabgp/api-open.conf --decode FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:003C:02:0000001C4001010040020040030465016501800404000000C840050400000064000000002001010101
  - env exabgp_log_enable=false nosetests --with-coverage ./qa/tests/*_test.py

after_success:
  - coveralls
  - ocular

notifications:
  irc:
    channels: "irc.freenode.org#exabgp"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/48936e41bd3f866cce4e
    # options: [always|never|change] default: always
    on_success: always
    on_failure: always
    on_start: false

